import { STEPS } from "./constants";

const VIDEO_SOCIAL_MEDIA_STEP = { step: STEPS.DOWNLOAD, subSteps: [], label: "Downloading Video" };
const TRANSCRIBE_STEP = { step: STEPS.TRANSCRIBE, subSteps: ["metaData"], label: "Transcribing Audio" };
const CROP_VIDEO_STEP = { step: STEPS.CROP_VIDEO, subSteps: ["srtTranscript", "wordTimestamps"], label: "Clipping & Cropping Videos" };
const FACE_DETECTION_AND_CROP_STEP = { step: STEPS.FACE_DETECTION_AND_CROP, subSteps: ["srtTranscript", "wordTimestamps"], label: "Face Detection, Clip & Crop" };
const CAPTIONS_STEP = { step: STEPS.CAPTION_CLIP, subSteps: [], label: "Captioning Clip" };
const DELETE_VIDEO_STEP = { step: STEPS.DELETE_VIDEO, subSteps: [], label: "Deleting Video" };

const GROUPS = {
  CROP_GROUP: [
    TRANSCRIBE_STEP,
    CROP_VIDEO_STEP,
    DELETE_VIDEO_STEP
  ],
  ZOOM_FACE_GROUP: [
    TRANSCRIBE_STEP,
    FACE_DETECTION_AND_CROP_STEP,
    DELETE_VIDEO_STEP
  ],
  CAPTION_CROP_GROUP: [
    TRANSCRIBE_STEP,
    CROP_VIDEO_STEP,
    CAPTIONS_STEP,
    DELETE_VIDEO_STEP
  ],
  CAPTION_ZOOM_FACE_GROUP: [
    TRANSCRIBE_STEP,
    FACE_DETECTION_AND_CROP_STEP,
    CAPTIONS_STEP,
    DELETE_VIDEO_STEP
  ]
};

export const PIPELINES = {
  VIDEO_SOCIAL_MEDIA: [
    VIDEO_SOCIAL_MEDIA_STEP,
    TRANSCRIBE_STEP,
    CROP_VIDEO_STEP,
    DELETE_VIDEO_STEP
  ],
  VIDEO_SOCIAL_MEDIA_ZOOM_FACE: [
    VIDEO_SOCIAL_MEDIA_STEP,
    ...GROUPS.ZOOM_FACE_GROUP
  ],
  VIDEO_SOCIAL_MEDIA_CROP: [
    VIDEO_SOCIAL_MEDIA_STEP,
    ...GROUPS.CROP_GROUP
  ],
  VIDEO_SOCIAL_MEDIA_CAPTION: [
    VIDEO_SOCIAL_MEDIA_STEP,
    ...GROUPS.CAPTION_CROP_GROUP
  ],
  VIDEO_SOCIAL_MEDIA_CAPTION_ZOOM_FACE: [
    VIDEO_SOCIAL_MEDIA_STEP,
    ...GROUPS.CAPTION_ZOOM_FACE_GROUP
  ],
  VIDEO_SOCIAL_MEDIA_CAPTION_CROP: [
    VIDEO_SOCIAL_MEDIA_STEP,
    ...GROUPS.CAPTION_CROP_GROUP
  ],

  DIRECT: [
    TRANSCRIBE_STEP,
    CROP_VIDEO_STEP
  ],
  DIRECT_ZOOM_FACE: GROUPS.ZOOM_FACE_GROUP,
  DIRECT_CROP: GROUPS.CROP_GROUP,
  DIRECT_CAPTION: GROUPS.CAPTION_CROP_GROUP,
  DIRECT_CAPTION_ZOOM_FACE: GROUPS.CAPTION_ZOOM_FACE_GROUP,
  DIRECT_CAPTION_CROP: GROUPS.CAPTION_CROP_GROUP,
};